# Utiliza una imagen base de Ubuntu
FROM amazoncorretto:21


# Install gradle
RUN yum install unzip -y
RUN yum install zip -y
RUN yum install shadow-utils -y

RUN useradd -u 1000 -m -d /home/developer developer
USER developer

WORKDIR /app

RUN curl -s "https://get.sdkman.io" | sh
RUN /bin/bash -c "source /home/developer/.sdkman/bin/sdkman-init.sh && sdk install gradle"

# Inicia el wrapper de gradle
#COPY settings.gradle /app/settings.gradle
#RUN /bin/bash -c "source /home/developer/.sdkman/bin/sdkman-init.sh && gradle wrapper"
#
## Asigna permisos de ejecución al script
#RUN chown -R 1000:1000 /app/.gradle/
