FROM amazoncorretto:21

# Install dependencies, including tar
RUN yum install -y unzip zip shadow-utils curl tar && yum clean all

# Install Node.js
RUN yum install -y https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm
RUN yum install -y nodejs --setopt=nodesource-nodejs.module_hotfixes=1
RUN node -v
RUN npm -v

# Create user and directories
RUN useradd -u 1000 -m -d /home/developer developer
RUN mkdir -p /_dev/app && chown -R 1000:1000 /_dev /_dev/app

USER developer
WORKDIR /dev

# Install SDKMAN and Gradle
RUN curl -s "https://get.sdkman.io" | bash
RUN /bin/bash -c "source /home/developer/.sdkman/bin/sdkman-init.sh && sdk install gradle"

# Copy and modify settings.gradle
COPY settings.gradle /_dev/settings.gradle
RUN sed -i 's/''app\//''app\/app\//g' /_dev/settings.gradle
RUN cat /_dev/settings.gradle
RUN ls -lart /_dev

# Copy package.json and install npm packages
COPY package.json /_dev/package.json

USER root
WORKDIR /_dev
RUN ls -lart
RUN npm install
