version: '3'
services:
  my-java-app:
    image: amazoncorretto:20
    volumes:
      - ./app:/app
    working_dir: /app
    command: ./gradlew run -t --args="-mortadelo -filemon"
    ports:
      - "8080:8080"
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"