/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mutiitu.blog.core;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import org.slf4j.LoggerFactory;

import com.google.inject.Guice;
import com.google.inject.Injector;

import io.javalin.Javalin;
import io.javalin.rendering.template.JavalinThymeleaf;
import mutiitu.blog.components.Header;

public class App {
    public String getGreeting() {
        return "Hello World  !";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        JavalinThymeleaf.init();

        var module = new AppModule();
        Injector injector = Guice.createInjector(module);


        var App = Javalin.create( config -> {

            var rootPath = Path.of(System.getProperty("user.dir")).getParent();
            var paths = new ArrayList<Path>();
            paths.add( Path.of(rootPath + "/main-module/src"));
            paths.add( Path.of(rootPath + "/persistence-module/src"));

            var autoShutdownPlugin = new AutoShutdownPlugin(paths);

            config.plugins.register(autoShutdownPlugin);
        })
            .get("/", ctx -> ctx.result("Hello World 111111"))
            .get("/jte", ctx -> ctx.render("hello.jte"))
            .get("/thymeleaf", ctx -> {
                    ctx.render("templates/hello.html");
            })
            .get("/header", ctx ->  {
                var header = injector.getInstance(Header.class);
                ctx.result(header.render()); 
            })
            .start(7070);

        System.out.println(App);

    }
}
