/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mutiitu.blog.core;

import java.nio.file.Paths;
import java.util.List;

import com.google.inject.Guice;
import com.google.inject.Injector;

import io.javalin.Javalin;
import io.javalin.rendering.template.JavalinThymeleaf;
import mutiitu.blog.components.Header;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        JavalinThymeleaf.init();

        var module = new AppModule();
        Injector injector = Guice.createInjector(module);


        var App = Javalin.create( config -> {

            var autoShutdownPlugin = new AutoShutdownPlugin(List.of(Paths.get("src", "main")));

            config.plugins.register(autoShutdownPlugin);
        })
            .get("/", ctx -> ctx.result("Hello World 2"))
            .get("/jte", ctx -> ctx.render("hello.jte"))
            .get("/thymeleaf", ctx -> {
                    ctx.render("templates/hello.html");
            })
            .get("/header", ctx ->  {
                var header = injector.getInstance(Header.class);
                ctx.result(header.render()); 
            })
            .start(7070);

        System.out.println(App);

    }
}
