/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mutiitu.framework.core;


public class App {
    public String getGreeting() {
        return "Hello World  !";
    }
}
